apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: registry
spec:
  storageClassName: persistent
  resources:
    requests:
      storage: 20Gi
  accessModes:
    - ReadWriteOnce
