apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-data-pvc
  namespace: redbot
spec:
  storageClassName: persistent
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
