apiVersion: v1
kind: PersistentVolume
metadata:
  name: redbot-cogs-pv
  namespace: redbot
spec:
  storageClassName: persistent
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/redbot-cogs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-cogs-pvc
  namespace: redbot
spec:
  storageClassName: persistent
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-data-pvc
  namespace: redbot
spec:
  storageClassName: persistent
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
