apiVersion: apps/v1
kind: Deployment
metadata:
  name: redbot-deployment
  namespace: redbot
  labels:
    app: redbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redbot
  template:
    metadata:
      labels:
        app: redbot
    spec:
      containers:
        - name: redbot
          image: phasecorex/red-discordbot:audio
          envFrom:
            - configMapRef:
                name: redbot-config
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: token
          volumeMounts:
            - name: redbot-data
              mountPath: /data
      volumes:
        - name: redbot-data
          persistentVolumeClaim:
            claimName: redbot-data-pvc
