apiVersion: v1
kind: Service
metadata:
  name: svc
spec:
  selector:
    app: hello
  ports:
    - port: 80
      targetPort: http
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    name: hello
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  # tls:
  #   - hosts:
  #       - hello.axatol.xyz
  #     secretName: hello-tls
  rules:
    #   - host: hello.axatol.xyz
    #     http:
    #       paths:
    #         - pathType: Prefix
    #           path: /
    #           backend:
    #             service:
    #               name: hello-svc
    #               port:
    #                 name: http
    - host: hello.k8s.axatol.home
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: svc
                port:
                  name: http
