apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: Secret
metadata:
  name: pihole-secret
  namespace: pihole
type: Opaque
data:
  webpassword: UGlob2xlQDEyMzQ1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: Australia/Brisbane
  PIHOLE_DNS: 8.8.8.8;8.8.4.4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-lists
  namespace: pihole
data:
  custom.list: |
    192.168.1.42 ssh.axatol.local
    192.168.1.43 nas.axatol.local
    192.168.1.128 axatol.xyz
    192.168.1.128 hello-world.axatol.xyz
    192.168.1.128 pihole.axatol.local
