apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pvc
  namespace: pihole
spec:
  storageClassName: ephemeral
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-pvc
  namespace: pihole
spec:
  storageClassName: ephemeral
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce
