apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: hello-world
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: http
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: hello-world
  labels:
    name: hello-world
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - hello-world.axatol.xyz
      secretName: hello-world-tls
  rules:
    - host: hello-world.axatol.xyz
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hello-world-svc
                port:
                  name: http
