apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: runner-autoscaler
spec:
  scaleTargetRef:
    name: runner-autoscaler
  scaleUpTriggers:
    - githubEvent: {}
      amount: 1
      duration: 5m
  minReplicas: 0
  maxReplicas: 3
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: semantic-release-gha-ci
spec:
  template:
    spec:
      image: public.ecr.aws/t4g8t3e5/gha-runner:latest
      repository: hans-m-song/semantic-release-gha
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: huisheng-ci
spec:
  template:
    spec:
      image: public.ecr.aws/t4g8t3e5/gha-runner:latest
      repository: hans-m-song/huisheng
