# https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
spec:
  replicas: 1
  persistence:
    storageClassName: ephemeral
    storage: 1Gi
  resources:
    requests:
      cpu: 100m
  rabbitmq:
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
  service:
    type: LoadBalancer
