apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-update
  namespace: ddns
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ddns-updater
              image: curlimages/curl
              command:
                - curl
                - https://$(USER):$(PASS)@$(ENDPOINT)?hostname=$(HOSTNAME)
              envFrom:
                - secretRef:
                    name: ddns-secret
                - configMapRef:
                    name: ddns-config
