apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ddns

resources:
  - ./namespace.yaml
  - ./cronjob.yaml

configMapGenerator:
  - name: config
    envs:
      - config.properties

secretGenerator:
  - name: credentials
    envs:
      - ./secrets.properties

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    type: kustomized
