apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  namespace: postgres
data:
  PG_DATA: /data/pgdata
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: UG9zdGdyZXNAMTIzNDU=
