apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
  namespace: postgres
spec:
  claimRef:
    kind: PersistentVolumeClaim
    name: postgres-data-pvc
    namespace: postgres
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /opt/postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: postgres
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
