apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres
          envFrom:
            - secretRef:
                name: postgres-password
            - configMapRef:
                name: postgres-env
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
