name: Build Runner

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - 'runner/**'
      - .github/workflows/build-runner.yaml

env:
  REGISTRY: public.ecr.aws/axatol
  REPOSITORY: gha-runner

jobs:
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Retrieve and tag last image
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
        run: |
          docker pull $IMAGE:latest
          docker tag $IMAGE:latest $IMAGE:previous
          docker push $IMAGE:previous

      - name: Build new image
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}
        run: |
          docker build --tag $IMAGE:latest --cache-from $IMAGE:previous ./runner
          docker push $IMAGE:latest

      - uses: hans-m-song/actions/prune-ecr-repository@master
        with:
          aws-access-key-id: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
          repository-name: ${{ env.REPOSITORY }}
