name: Build Runner

on:
  workflow_dispatch:
  schedule:
    # once a month
    - cron: "0 0 1 * *"

  push:
    branches:
      - master
    paths:
      - "runner/**"
      - .github/workflows/build-runner.yaml
      - .github/workflows/runner-tool-cache.yaml

permissions:
  id-token: write
  contents: read

env:
  image: public.ecr.aws/axatol/github-actions-runner

jobs:
  build:
    name: Build

    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ECR_IMAGE_PUBLISHER_ROLE_ARN }}
          role-session-name: ${{ github.triggering_actor }}-kube-stack-${{ github.job }}-${{ github.run_id }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - uses: axatol/actions/docker-build-push@release
        with:
          image: ${{ env.image }}
          build-context: ./runner

      - uses: axatol/actions/prune-ecr-repository@release
        with:
          repository-name: ${{ env.image }}

  tools:
    name: Populate runner tool cache

    needs:
      - build

    uses: ./.github/workflows/runner-tool-cache.yaml
