name: Populate runner tool cache

on:
  workflow_call:

jobs:
  cache:
    runs-on:
      - self-hosted

    strategy:
      matrix:
        target:
          - { tool: node, version: '14' }
          - { tool: node, version: '16' }
          - { tool: python, version: '3.10' }
          - { tool: go, version: '1.18' }

    steps:
      - uses: actions/setup-node@v3
        if: matrix.target.tool == 'node'
        with:
          node-version: ${{ matrix.target.version }}

      - uses: actions/setup-python@v3
        if: matrix.target.tool == 'python'
        with:
          python-version: ${{ matrix.target.version }}

      - uses: actions/setup-go@v3
        if: matrix.target.tool == 'go'
        with:
          go-version: ${{ matrix.target.version }}
